'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AnimatePresence } from "framer-motion";
import { GeneralAppContext } from "./context/AppContext";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AnimatePresence>
        <GeneralAppContext>
          <body className={inter.className}>{children}</body>
        </GeneralAppContext>
      </AnimatePresence>
    </html>
  );
}
